# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=64)),
                ('profile', models.TextField(null=True)),
                ('content', models.TextField(null=True)),
                ('pub_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
